### ISSUE TITLE
Can't run NFT examples locally 

### ISSUE THREAD

**Issue by SystemDiagnosticss** [kalwalt/kalwalt-interactivity-AR#1]
Hello. That's amazing work. Your examles work on glitch but don't work locally.

I have two errors in console:

1) nft_threads_duck.html:1 Access to XMLHttpRequest at 'file:///home/fulltimerobotics/Desktop/kalwalt-interactivity-AR-master/resources/data/camera_para-iPhone%205%20rear%20640x480%201.0m.dat' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

2) resources/data/camera_para-iPhone%205%20rear%20640x480%201.0m.dat:1 Failed to load resource: net::ERR_FAILED

Also video streaming can't start. Any idea?

**Comment by kalwalt** [comment]
@SystemDiagnosticss i didn't try with a local server, because i would share with other people to test the new threaded version, but are you sure that you run it with a server? Reading the first error seems like you didn't run a server. I will check but i wolud know the performances with the example and with which devices are you testing it.

**Comment by kalwalt** [comment]
It works for me with a python server, try in a console to run:
```
python -m SimpleHTTPServer
```
Anyway i have to fix some small things.

**Comment by SystemDiagnosticss** [comment]
Thaks, bro. It's work !!!

**Comment by SystemDiagnosticss** [comment]
Solved
