### ISSUE TITLE
Multiple NFT marker 

### ISSUE THREAD

**Issue by SystemDiagnosticss** [kalwalt/kalwalt-interactivity-AR#2]
@kalwalt Hello. Is it possible work with multiple NFT-marker in current version library? I try reconize simultaneous nft marker(image) and ar-maker with your example and IT'S WORK!!
 
![untitled](https://user-images.githubusercontent.com/15822541/66405473-dc5dc100-e9f2-11e9-9c76-013bcbe8d1cb.png)

**But how I can load many nft-markers and ar-makers ??**

**Comment by kalwalt** [comment]
@SystemDiagnosticss thats good!  I haven't a clear idea on how to do right now, because my first pourpose is simply to test the threaded version of my jsartoolkit5 version. The problem if you read in my [PR](https://github.com/kalwalt/jsartoolkit5/pull/2) at the beginning, you need to enable the SharedArrayBuffer option in the browser, that means you are exposed to the Spectre issue, that i don't feel very confortable with it, but maybe in a near future this will be solved and we can release it. 
Coming back to the question probably doing an array of NFT markers will do the tricks but i think that could be a performance issue. Anyway this will be a feature to be added in another time i think...

**Comment by SystemDiagnosticss** [comment]
@kalwalt Look on this https://www.youtube.com/watch?v=gNSj3LF1LiY and this http://www.artoolkitx.org/ . If i understand right artoolkit can detect multiply nft markers but don't have implementation on javascript ..

**Comment by kalwalt** [comment]
> @kalwalt Look on this https://www.youtube.com/watch?v=gNSj3LF1LiY and this http://www.artoolkitx.org/ . If i understand right artoolkit can detect multiply nft markers but don't have implementation on javascript ..

thanks i will look this.

**Comment by kalwalt** [comment]
Multi NFT example here: https://kalwalt.github.io/kalwalt-interactivity-AR/nft/nft_simple_multi_markers.html

**Comment by kalwalt** [comment]
**ARnft** has now multi NFT support see PR https://github.com/webarkit/ARnft/pull/199
